[package]
name = "game"
description = "Chaos FC: the Bevy application."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "chaos-fc"
path = "src/main.rs"

[dependencies]
asset-bridge.workspace = true
bevy.workspace = true
bevy-bridge.workspace = true
retarget.workspace = true

[dev-dependencies]
tempfile.workspace = true
